import os

# NetSuite
NETSUITE_ACCOUNT_ID = os.getenv("NETSUITE_ACCOUNT_ID")
NETSUITE_CLIENT_ID = os.getenv("NETSUITE_CLIENT_ID")
NETSUITE_CLIENT_SECRET = os.getenv("NETSUITE_CLIENT_SECRET")
NETSUITE_REFRESH_TOKEN = os.getenv("NETSUITE_REFRESH_TOKEN")

# Redis
UPSTASH_REDIS_URL = os.getenv("UPSTASH_REDIS_URL")
UPSTASH_REDIS_TOKEN = os.getenv("UPSTASH_REDIS_TOKEN")

# Power BI
POWERBI_API_KEY = os.getenv("POWERBI_API_KEY")

# Webhook
WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET")