import os

# NetSuite OAuth
NETSUITE_ACCOUNT_ID = os.getenv("NETSUITE_ACCOUNT_ID")
CLIENT_ID = os.getenv("NETSUITE_CLIENT_ID")
CLIENT_SECRET = os.getenv("NETSUITE_CLIENT_SECRET")
REFRESH_TOKEN = os.getenv("NETSUITE_REFRESH_TOKEN")

# Power BI
POWERBI_API_KEY = os.getenv("POWERBI_API_KEY")
